CREATE SCHEMA IF NOT EXISTS knowhow_management;

CREATE TABLE IF NOT EXISTS knowhow_management.major_categories (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       integer NOT NULL,
    name          text    NOT NULL,
    display_order integer NOT NULL,
    is_deleted    boolean NOT NULL DEFAULT false,
    CONSTRAINT major_categories_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE RESTRICT,
    CONSTRAINT major_categories_name_not_empty CHECK (char_length(name) > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS major_categories_user_name_active_uidx
    ON knowhow_management.major_categories (user_id, name)
    WHERE is_deleted = false;

CREATE INDEX IF NOT EXISTS major_categories_user_active_idx
    ON knowhow_management.major_categories (user_id)
    WHERE is_deleted = false;

CREATE TABLE IF NOT EXISTS knowhow_management.middle_categories (
    id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           integer NOT NULL,
    major_category_id integer NOT NULL,
    name              text    NOT NULL,
    display_order     integer NOT NULL,
    is_deleted        boolean NOT NULL DEFAULT false,
    CONSTRAINT middle_categories_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE RESTRICT,
    CONSTRAINT middle_categories_major_category_id_fkey
        FOREIGN KEY (major_category_id) REFERENCES knowhow_management.major_categories (id) ON DELETE RESTRICT,
    CONSTRAINT middle_categories_name_not_empty CHECK (char_length(name) > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS middle_categories_major_name_active_uidx
    ON knowhow_management.middle_categories (major_category_id, name)
    WHERE is_deleted = false;

CREATE INDEX IF NOT EXISTS middle_categories_major_active_idx
    ON knowhow_management.middle_categories (major_category_id)
    WHERE is_deleted = false;

CREATE INDEX IF NOT EXISTS middle_categories_user_active_idx
    ON knowhow_management.middle_categories (user_id)
    WHERE is_deleted = false;

CREATE TABLE IF NOT EXISTS knowhow_management.knowhows (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             integer NOT NULL,
    middle_category_id  integer NULL,
    title               text    NOT NULL,
    keywords            text,
    content             text    NOT NULL,
    display_order       integer NOT NULL,
    is_deleted          boolean NOT NULL DEFAULT false,
    CONSTRAINT knowhows_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE RESTRICT,
    CONSTRAINT knowhows_middle_category_id_fkey
        FOREIGN KEY (middle_category_id) REFERENCES knowhow_management.middle_categories (id) ON DELETE RESTRICT,
    CONSTRAINT knowhows_title_not_empty CHECK (char_length(title) > 0),
    CONSTRAINT knowhows_content_not_empty CHECK (char_length(content) > 0)
);

CREATE INDEX IF NOT EXISTS knowhows_user_middle_active_idx
    ON knowhow_management.knowhows (user_id, middle_category_id)
    WHERE is_deleted = false;

CREATE INDEX IF NOT EXISTS knowhows_user_active_idx
    ON knowhow_management.knowhows (user_id)
    WHERE is_deleted = false;
