-- ユーザ休日は全機能が祝日判定に使う共通データのため public に置く（rules/13-db.md の例外）。
CREATE TABLE IF NOT EXISTS public.user_holidays (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL,
    holiday_date date NOT NULL,
    name varchar(255) NOT NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    CONSTRAINT user_holidays_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE RESTRICT,
    CONSTRAINT user_holidays_name_not_empty CHECK (char_length(name) > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS user_holidays_user_date_active_uidx
    ON public.user_holidays (user_id, holiday_date)
    WHERE is_deleted = false;

CREATE INDEX IF NOT EXISTS user_holidays_user_date_active_idx
    ON public.user_holidays (user_id, holiday_date)
    WHERE is_deleted = false;

-- 既存の DB: schedule.user_holidays の行を id を保って移し、行数が一致したら旧表を削除する（べき等）。
DO $$
DECLARE
    src_count bigint;
    dst_count bigint;
BEGIN
    IF to_regclass('schedule.user_holidays') IS NOT NULL THEN
        INSERT INTO public.user_holidays (id, user_id, holiday_date, name, is_deleted)
        OVERRIDING SYSTEM VALUE
        SELECT id, user_id, holiday_date, name, is_deleted
        FROM schedule.user_holidays o
        WHERE NOT EXISTS (SELECT 1 FROM public.user_holidays n WHERE n.id = o.id);

        PERFORM setval(
            pg_get_serial_sequence('public.user_holidays', 'id'),
            GREATEST((SELECT COALESCE(MAX(id), 0) FROM public.user_holidays), 1),
            (SELECT COUNT(*) > 0 FROM public.user_holidays)
        );

        SELECT COUNT(*) INTO src_count FROM schedule.user_holidays;
        SELECT COUNT(*) INTO dst_count
        FROM public.user_holidays n
        WHERE EXISTS (SELECT 1 FROM schedule.user_holidays o WHERE o.id = n.id);
        IF src_count <> dst_count THEN
            RAISE EXCEPTION 'user_holidays の移行件数が一致しません (% / %)', src_count, dst_count;
        END IF;
        DROP TABLE schedule.user_holidays;
    END IF;
END $$;
