-- public.api_keys（api-key-management が作成する。portal の DDL を先に適用しておく）

CREATE TABLE IF NOT EXISTS public.api_keys (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL,
    name varchar(100) NOT NULL,
    key_hash char(64) NOT NULL,
    key_prefix varchar(12) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    expires_at timestamptz NULL,
    last_used_at timestamptz NULL,
    revoked_at timestamptz NULL,
    CONSTRAINT api_keys_key_hash_key UNIQUE (key_hash),
    CONSTRAINT api_keys_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE RESTRICT,
    CONSTRAINT api_keys_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT api_keys_expires_after_created CHECK (expires_at IS NULL OR expires_at > created_at),
    CONSTRAINT api_keys_revoked_after_created CHECK (revoked_at IS NULL OR revoked_at >= created_at)
);

CREATE INDEX IF NOT EXISTS api_keys_user_created_idx
    ON public.api_keys (user_id, created_at DESC);
