CREATE SCHEMA IF NOT EXISTS password_management;

CREATE TABLE IF NOT EXISTS password_management.entries (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       integer NOT NULL,
    title         text    NOT NULL,
    userword      text    NOT NULL,
    psword        text    NOT NULL,
    site          text,
    memo          text,
    is_deleted    boolean NOT NULL DEFAULT false,
    CONSTRAINT entries_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE RESTRICT,
    CONSTRAINT entries_title_not_empty CHECK (char_length(title) > 0),
    CONSTRAINT entries_userword_not_empty CHECK (char_length(userword) > 0),
    CONSTRAINT entries_psword_not_empty CHECK (char_length(psword) > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS entries_user_title_active_uidx
    ON password_management.entries (user_id, title)
    WHERE is_deleted = false;

CREATE INDEX IF NOT EXISTS entries_user_active_idx
    ON password_management.entries (user_id)
    WHERE is_deleted = false;
