"""password-management からの取り込みのテスト（REQ-010 / design.md 取り込み）。

取り込み元は、テスト用のスキーマ（password_management と同じ構造）に作り、終わったら消す。
"""

from __future__ import annotations

import importlib.util
import sys
import uuid
from collections.abc import Callable, Iterator
from pathlib import Path
from typing import Any

import pytest
from fastapi.testclient import TestClient

from app.db import connect
from app.logger import LOG_FILE
from conftest import Owner, execute

SCRIPT = Path(__file__).resolve().parent.parent / "backend" / "scripts" / "import_password_management.py"
_spec = importlib.util.spec_from_file_location("import_password_management", SCRIPT)
assert _spec is not None and _spec.loader is not None
imp = importlib.util.module_from_spec(_spec)
sys.modules["import_password_management"] = imp  # dataclass が、モジュールを名前で引くため
_spec.loader.exec_module(imp)  # type: ignore[union-attr]


@pytest.fixture()
def source() -> Iterator[str]:
    schema = f"cm_import_src_{uuid.uuid4().hex[:10]}"
    execute(f"CREATE SCHEMA {schema}")
    execute(
        f"""
        CREATE TABLE {schema}.entries (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id integer NOT NULL REFERENCES public.users (id),
            title text NOT NULL, userword text NOT NULL, psword text NOT NULL,
            site text, memo text, is_deleted boolean NOT NULL DEFAULT false
        )
        """
    )
    yield schema
    execute(f"DROP SCHEMA {schema} CASCADE")


def _entry(schema: str, owner: Owner, title: str, user: str = "taro", pw: str = "pw", **cols: Any) -> int:
    cols = {"user_id": owner.id, "title": title, "userword": user, "psword": pw, **cols}
    keys = ", ".join(cols)
    marks = ", ".join(["%s"] * len(cols))
    return int(
        execute(f"INSERT INTO {schema}.entries ({keys}) VALUES ({marks}) RETURNING id", tuple(cols.values()))[0]["id"]
    )


def _run(schema: str, commit: bool = True) -> Any:
    conn = connect()
    try:
        result = imp.run_import(conn, schema)
        if commit:
            conn.commit()
        else:
            conn.rollback()
        return result
    finally:
        conn.close()


def _contracts(owner: Owner) -> list[dict[str, Any]]:
    return execute("SELECT * FROM contract_management.contracts WHERE user_id = %s ORDER BY id", (owner.id,))


def _source_rows(schema: str) -> list[dict[str, Any]]:
    return execute(f"SELECT * FROM {schema}.entries ORDER BY id")


def test_import_maps_fields_and_defaults(make_owner: Callable[..., Owner], source: str) -> None:
    owner = make_owner()
    e1 = _entry(source, owner, "  Googleアカウント  ", user=" me@example.com ", pw="  複数\n行  ", site=" https://g.example ", memo="メモ")
    e2 = _entry(source, owner, "サイトとメモなし", site=None, memo=None)
    e3 = _entry(source, owner, "空のサイト・メモ", site="   ", memo="")
    result = _run(source)
    assert (result.target, result.imported, result.already_imported, result.failures) == (3, 3, 0, [])
    rows = _contracts(owner)
    assert [r["imported_from_entry_id"] for r in rows] == [e1, e2, e3]
    first = rows[0]
    assert first["name"] == "Googleアカウント" and first["username"] == "me@example.com"
    assert first["password"] == "  複数\n行  "  # パスワードは、そのまま（空白・改行を含めて）
    assert first["homepage"] == "https://g.example" and first["memo"] == "メモ"
    for r in rows:
        assert (r["has_contract"], r["status"], r["login_password"], r["is_deleted"]) == (False, "active", True, False)
        assert not (r["login_passkey"] or r["login_2fa_mail"] or r["login_2fa_tel"])
        assert r["fee_amount"] is None and r["cancellation_method"] is None and r["payment_contract_id"] is None
    assert (rows[1]["homepage"], rows[1]["memo"]) == (None, None)
    assert (rows[2]["homepage"], rows[2]["memo"]) == (None, None)
    # 区分は「その他」（利用者ごとに作られる）
    cats = execute("SELECT id, name, is_default FROM contract_management.categories WHERE user_id = %s", (owner.id,))
    assert [(c["name"], c["is_default"]) for c in cats] == [("その他", True)]
    assert {r["category_id"] for r in rows} == {cats[0]["id"]}


def test_each_users_entries_go_to_that_user(make_owner: Callable[..., Owner], source: str) -> None:
    a = make_owner()
    b = make_owner()
    _entry(source, a, "共通の名前", user="ua", pw="pa")
    _entry(source, b, "共通の名前", user="ub", pw="pb")
    _entry(source, b, "Bだけ")
    result = _run(source)
    assert result.imported == 3
    assert [(r["name"], r["username"], r["password"]) for r in _contracts(a)] == [("共通の名前", "ua", "pa")]
    assert [(r["name"], r["username"]) for r in _contracts(b)] == [("共通の名前", "ub"), ("Bだけ", "taro")]
    # 区分は、利用者ごとに 1 つずつ
    for owner in (a, b):
        cats = execute("SELECT name FROM contract_management.categories WHERE user_id = %s", (owner.id,))
        assert [c["name"] for c in cats] == ["その他"]


def test_deleted_entries_and_deleted_users_are_not_imported(make_owner: Callable[..., Owner], source: str) -> None:
    alive = make_owner()
    gone = make_owner()
    _entry(source, alive, "生きている")
    _entry(source, alive, "削除済み", is_deleted=True)
    _entry(source, gone, "削除済みの利用者のエントリ")
    execute("UPDATE public.users SET is_deleted = true WHERE id = %s", (gone.id,))
    result = _run(source)
    assert (result.target, result.imported, result.skipped_deleted_user) == (1, 1, 1)
    assert [r["name"] for r in _contracts(alive)] == ["生きている"]
    assert _contracts(gone) == []


def test_rerun_does_not_duplicate_and_picks_up_new_entries(make_owner: Callable[..., Owner], source: str) -> None:
    owner = make_owner()
    _entry(source, owner, "一つ目")
    _entry(source, owner, "二つ目")
    assert _run(source).imported == 2
    again = _run(source)
    assert (again.target, again.imported, again.already_imported) == (2, 0, 2)
    assert len(_contracts(owner)) == 2
    _entry(source, owner, "三つ目")
    third = _run(source)
    assert (third.imported, third.already_imported) == (1, 2)
    assert [r["name"] for r in _contracts(owner)] == ["一つ目", "二つ目", "三つ目"]
    # 取り込んだ契約を編集しても、再実行で上書き・重複しない
    execute("UPDATE contract_management.contracts SET name = '編集済み' WHERE user_id = %s AND name = '一つ目'", (owner.id,))
    assert _run(source).imported == 0
    assert "編集済み" in [r["name"] for r in _contracts(owner)] and len(_contracts(owner)) == 3


def test_source_is_not_changed(make_owner: Callable[..., Owner], source: str) -> None:
    owner = make_owner()
    _entry(source, owner, "a", site="https://x", memo="m")
    _entry(source, owner, "b", is_deleted=True)
    before = _source_rows(source)
    _run(source)
    _run(source)
    assert _source_rows(source) == before


def test_dry_run_writes_nothing(make_owner: Callable[..., Owner], source: str) -> None:
    owner = make_owner()
    _entry(source, owner, "ドライラン")
    result = _run(source, commit=False)
    assert result.imported == 1  # 取り込む予定の件数
    assert _contracts(owner) == []
    assert execute("SELECT count(*) AS n FROM contract_management.categories WHERE user_id = %s", (owner.id,))[0]["n"] == 0


def test_failures_do_not_stop_the_others(make_owner: Callable[..., Owner], source: str) -> None:
    owner = make_owner()
    ok1 = _entry(source, owner, "正常1")
    long_title = _entry(source, owner, "あ" * 201)
    blank_title = _entry(source, owner, "   ")
    ok2 = _entry(source, owner, "正常2")
    result = _run(source)
    assert result.imported == 2 and result.target == 4
    assert {entry_id for entry_id, _ in result.failures} == {long_title, blank_title}
    assert all(reason for _, reason in result.failures)
    assert [r["imported_from_entry_id"] for r in _contracts(owner)] == [ok1, ok2]


def test_main_output_and_log_have_no_secrets(
    make_owner: Callable[..., Owner], source: str, capsys: pytest.CaptureFixture[str], log_dir: Path
) -> None:
    owner = make_owner()
    _entry(source, owner, "秘密のタイトル", user="secret-user-name", pw="S3cret-Pass", memo="秘密のメモ")
    _entry(source, owner, "い" * 201, user="secret-user-2", pw="S3cret-Pass-2")  # 失敗する行
    code = imp.main(["--source-schema", source])
    out = capsys.readouterr()
    text = out.out + out.err + (log_dir / LOG_FILE).read_text(encoding="utf-8")
    assert code == 1  # 取り込めなかった行がある
    assert "取り込み完了" in out.out and "対象のエントリ: 2 件" in out.out and "取り込み: 1 件" in out.out
    assert "取り込めなかった: 1 件" in out.out and "エントリ ID" in out.out
    for secret in ("秘密のタイトル", "secret-user-name", "S3cret-Pass", "secret-user-2", "秘密のメモ", "い" * 50):
        assert secret not in text, secret
    assert len(_contracts(owner)) == 1


def test_main_dry_run_and_exit_code(make_owner: Callable[..., Owner], source: str, capsys: pytest.CaptureFixture[str]) -> None:
    owner = make_owner()
    _entry(source, owner, "一件")
    assert imp.main(["--source-schema", source, "--dry-run"]) == 0
    out = capsys.readouterr().out
    assert "ドライラン" in out and "書き込みなし" in out and "取り込み（予定）: 1 件" in out
    assert _contracts(owner) == []
    assert imp.main(["--source-schema", source]) == 0
    assert len(_contracts(owner)) == 1
    assert imp.main(["--source-schema", source]) == 0  # 再実行
    assert "取り込み済みのためスキップ: 1 件" in capsys.readouterr().out
    assert len(_contracts(owner)) == 1


def test_missing_or_invalid_source(capsys: pytest.CaptureFixture[str]) -> None:
    assert imp.main(["--source-schema", "no_such_schema_" + uuid.uuid4().hex[:6]]) == 2
    assert "取り込めません" in capsys.readouterr().err
    assert imp.main(["--source-schema", "bad; DROP SCHEMA public"]) == 2
    assert "取り込めません" in capsys.readouterr().err


def test_imported_contracts_work_through_the_api(
    make_owner: Callable[..., Owner], make_client: Callable[..., TestClient], source: str
) -> None:
    owner = make_owner()
    _entry(source, owner, "移行したアカウント", user="taro", pw="migrated-pw", site="https://m.example")
    _run(source)
    c = make_client(owner)
    [item] = c.get("/accounts").json()["items"]
    assert item["name"] == "移行したアカウント" and item["username"] == "taro" and item["has_password"] is True
    assert c.get(f"/contracts/{item['id']}/password").json() == {"password": "migrated-pw"}
    detail = c.get(f"/contracts/{item['id']}").json()
    assert detail["has_contract"] is False and detail["category"]["name"] == "その他" and detail["login_methods"] == ["password"]
    # 画面から、通常の契約と同じように編集できる（取り込み元の ID は変わらない）
    res = c.patch(f"/contracts/{item['id']}", json={"name": "改名", "has_contract": False, "login_methods": ["password"], "username": "taro"})
    assert res.status_code == 200 and c.get(f"/contracts/{item['id']}/password").json() == {"password": "migrated-pw"}
