-- 定期実行の定義。1 つの部屋に対するもので、利用者ごとには分けない（作成者だけ残す）
CREATE TABLE IF NOT EXISTS room.room_schedules (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by_user_id integer NOT NULL,
    condition_type varchar(16) NOT NULL,
    run_time time NOT NULL,
    scene varchar(32) NOT NULL,
    is_enabled boolean NOT NULL DEFAULT true,
    last_run_at timestamptz NULL,
    last_run_result varchar(16) NULL,
    last_failed_devices text[] NOT NULL DEFAULT '{}',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT room_schedules_created_by_fkey
        FOREIGN KEY (created_by_user_id) REFERENCES public.users (id) ON DELETE RESTRICT,
    CONSTRAINT room_schedules_condition_type_check
        CHECK (condition_type IN ('daily', 'weekdays', 'holiday')),
    CONSTRAINT room_schedules_scene_check
        CHECK (scene IN ('indoor_speaker', 'bedside_speaker', 'ceiling_light', 'indirect_light', 'out')),
    CONSTRAINT room_schedules_last_run_result_check
        CHECK (last_run_result IN ('success', 'partial', 'failure')),
    -- 最終実行の日時と結果は一緒に入る
    CONSTRAINT room_schedules_last_run_pair_check
        CHECK ((last_run_at IS NULL) = (last_run_result IS NULL)),
    CONSTRAINT room_schedules_failed_devices_check
        CHECK (last_failed_devices <@ ARRAY['ceiling_light', 'indirect_light', 'indoor_speaker', 'bedside_speaker']::text[]),
    -- 時と分の指定（秒は常に 0）
    CONSTRAINT room_schedules_run_time_check
        CHECK (date_part('second', run_time) = 0)
);

CREATE INDEX IF NOT EXISTS ix_room_schedules_enabled
    ON room.room_schedules (is_enabled);

CREATE INDEX IF NOT EXISTS ix_room_schedules_run_time
    ON room.room_schedules (run_time, scene);

-- 曜日の指定の定期実行が、どの曜日に実行されるか（1 = 月曜 … 7 = 日曜）
CREATE TABLE IF NOT EXISTS room.schedule_weekdays (
    schedule_id bigint NOT NULL,
    weekday smallint NOT NULL,
    PRIMARY KEY (schedule_id, weekday),
    CONSTRAINT schedule_weekdays_schedule_fkey
        FOREIGN KEY (schedule_id) REFERENCES room.room_schedules (id) ON DELETE CASCADE,
    CONSTRAINT schedule_weekdays_weekday_check
        CHECK (weekday BETWEEN 1 AND 7)
);

-- ある日に実行したことの記録。同じ日の重複実行を防ぐ印
CREATE TABLE IF NOT EXISTS room.schedule_runs (
    schedule_id bigint NOT NULL,
    run_date date NOT NULL,
    started_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (schedule_id, run_date),
    CONSTRAINT schedule_runs_schedule_fkey
        FOREIGN KEY (schedule_id) REFERENCES room.room_schedules (id) ON DELETE CASCADE
);
