-- recipe-management（レシピ管理）のスキーマ。db-design.md に対応する。
-- 何度実行しても同じ結果になる（IF NOT EXISTS / ON CONFLICT DO NOTHING）。

CREATE SCHEMA IF NOT EXISTS recipe_management;

-- 材料（user_id が NULL の行は全利用者共通）
CREATE TABLE IF NOT EXISTS recipe_management.ingredients (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     integer NULL,
    name        text NOT NULL,
    kana        text NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ingredients_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE RESTRICT,
    CONSTRAINT ingredients_name_not_blank CHECK (char_length(btrim(name)) > 0),
    CONSTRAINT ingredients_kana_not_blank CHECK (char_length(btrim(kana)) > 0)
);

-- NULL は通常の一意制約では重複できるため、共通と独自で部分一意に分ける
CREATE UNIQUE INDEX IF NOT EXISTS ingredients_system_name_uidx
    ON recipe_management.ingredients (name)
    WHERE user_id IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ingredients_user_name_uidx
    ON recipe_management.ingredients (user_id, name)
    WHERE user_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS ingredients_kana_idx
    ON recipe_management.ingredients (kana, id);

-- 分量名称（user_id が NULL の行は全利用者共通）
CREATE TABLE IF NOT EXISTS recipe_management.measurements (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      integer NULL,
    name_bef     text NOT NULL DEFAULT '',
    name_aft     text NOT NULL DEFAULT '',
    ness_amount  boolean NOT NULL,
    created_at   timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT measurements_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE RESTRICT,
    CONSTRAINT measurements_not_both_empty CHECK (name_bef <> '' OR name_aft <> '')
);

CREATE UNIQUE INDEX IF NOT EXISTS measurements_system_uidx
    ON recipe_management.measurements (name_bef, name_aft)
    WHERE user_id IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS measurements_user_uidx
    ON recipe_management.measurements (user_id, name_bef, name_aft)
    WHERE user_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS measurements_order_idx
    ON recipe_management.measurements (name_bef, name_aft, id);

-- レシピ（論理削除する）
CREATE TABLE IF NOT EXISTS recipe_management.recipes (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     integer NOT NULL,
    name        text NOT NULL,
    kana        text NOT NULL,
    is_deleted  boolean NOT NULL DEFAULT false,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT recipes_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE RESTRICT,
    CONSTRAINT recipes_name_not_blank CHECK (char_length(btrim(name)) > 0),
    CONSTRAINT recipes_kana_not_blank CHECK (char_length(btrim(kana)) > 0)
);

-- 削除されていないレシピの間だけ、メニュー名を一意にする（削除後の同名の再登録を許す）
CREATE UNIQUE INDEX IF NOT EXISTS recipes_user_name_active_uidx
    ON recipe_management.recipes (user_id, name)
    WHERE is_deleted = false;

CREATE INDEX IF NOT EXISTS recipes_user_kana_idx
    ON recipe_management.recipes (user_id, kana, id)
    WHERE is_deleted = false;

-- 工程
CREATE TABLE IF NOT EXISTS recipe_management.recipe_steps (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id    integer NOT NULL,
    step_no      integer NOT NULL,
    description  text NOT NULL,
    CONSTRAINT recipe_steps_recipe_id_fkey
        FOREIGN KEY (recipe_id) REFERENCES recipe_management.recipes (id) ON DELETE CASCADE,
    CONSTRAINT recipe_steps_recipe_step_key UNIQUE (recipe_id, step_no),
    CONSTRAINT recipe_steps_step_no_check CHECK (step_no >= 1),
    CONSTRAINT recipe_steps_description_not_blank CHECK (char_length(btrim(description)) > 0)
);

-- 工程の材料の行
CREATE TABLE IF NOT EXISTS recipe_management.recipe_step_items (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    step_id         integer NOT NULL,
    item_no         integer NOT NULL,
    ingredient_id   integer NOT NULL,
    measurement_id  integer NOT NULL,
    amount          text NOT NULL DEFAULT '',
    CONSTRAINT recipe_step_items_step_id_fkey
        FOREIGN KEY (step_id) REFERENCES recipe_management.recipe_steps (id) ON DELETE CASCADE,
    CONSTRAINT recipe_step_items_ingredient_id_fkey
        FOREIGN KEY (ingredient_id) REFERENCES recipe_management.ingredients (id) ON DELETE RESTRICT,
    CONSTRAINT recipe_step_items_measurement_id_fkey
        FOREIGN KEY (measurement_id) REFERENCES recipe_management.measurements (id) ON DELETE RESTRICT,
    CONSTRAINT recipe_step_items_step_item_key UNIQUE (step_id, item_no),
    CONSTRAINT recipe_step_items_item_no_check CHECK (item_no >= 1)
);

CREATE INDEX IF NOT EXISTS recipe_step_items_ingredient_idx
    ON recipe_management.recipe_step_items (ingredient_id);

CREATE INDEX IF NOT EXISTS recipe_step_items_measurement_idx
    ON recipe_management.recipe_step_items (measurement_id);

-- 全利用者共通の材料（初期データ）
INSERT INTO recipe_management.ingredients (user_id, name, kana)
VALUES
    (NULL, '砂糖', 'さとう'),
    (NULL, '塩', 'しお'),
    (NULL, '胡椒', 'こしょう'),
    (NULL, '醤油', 'しょうゆ'),
    (NULL, 'みりん', 'みりん'),
    (NULL, '酒', 'さけ'),
    (NULL, '味噌', 'みそ'),
    (NULL, 'サラダ油', 'さらだあぶら'),
    (NULL, '卵', 'たまご'),
    (NULL, '牛乳', 'ぎゅうにゅう'),
    (NULL, 'バター', 'ばたー'),
    (NULL, '豆板醤', 'とうばんじゃん')
ON CONFLICT (name) WHERE user_id IS NULL DO NOTHING;

-- 全利用者共通の分量名称（初期データ）
INSERT INTO recipe_management.measurements (user_id, name_bef, name_aft, ness_amount)
VALUES
    (NULL, '小さじ', '', true),
    (NULL, '大さじ', '', true),
    (NULL, '', 'cc', true),
    (NULL, 'ひとつまみ', '', false)
ON CONFLICT (name_bef, name_aft) WHERE user_id IS NULL DO NOTHING;
