-- contract-management のスキーマ（db-design.md）。再実行できる（IF NOT EXISTS）。
-- 前提: portal の DDL（public.users）と api-key-management の DDL（public.api_keys）を先に適用しておく。

CREATE TABLE IF NOT EXISTS contract_management.categories (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL,
    name varchar(100) NOT NULL,
    is_default boolean NOT NULL DEFAULT false,
    is_financial boolean NOT NULL DEFAULT false,
    is_deleted boolean NOT NULL DEFAULT false,
    CONSTRAINT categories_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE RESTRICT,
    CONSTRAINT categories_name_not_empty CHECK (char_length(name) > 0),
    CONSTRAINT categories_default_not_deleted CHECK (NOT (is_default AND is_deleted)),
    CONSTRAINT categories_default_not_financial CHECK (NOT (is_default AND is_financial))
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_categories_user_name
    ON contract_management.categories (user_id, name)
    WHERE is_deleted = false;

CREATE UNIQUE INDEX IF NOT EXISTS ux_categories_user_default
    ON contract_management.categories (user_id)
    WHERE is_default = true;

CREATE TABLE IF NOT EXISTS contract_management.contracts (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL,
    category_id integer NOT NULL,
    name varchar(200) NOT NULL,
    has_contract boolean NOT NULL DEFAULT true,
    status varchar(10) NOT NULL DEFAULT 'active',
    homepage text NULL,
    memo text NULL,
    login_password boolean NOT NULL DEFAULT false,
    login_passkey boolean NOT NULL DEFAULT false,
    login_2fa_mail boolean NOT NULL DEFAULT false,
    login_2fa_tel boolean NOT NULL DEFAULT false,
    twofa_mail_address text NULL,
    twofa_tel_number text NULL,
    username text NULL,
    password text NULL,
    registered_email text NULL,
    fee_amount integer NULL,
    fee_cycle varchar(10) NULL,
    renewal_date date NULL,
    contract_date date NULL,
    contract_date_precision varchar(10) NULL,
    trial_end_date date NULL,
    end_date date NULL,
    auto_renewal boolean NULL,
    holder_name text NULL,
    member_number text NULL,
    cancel_notice_days integer NULL,
    cancellation_fee text NULL,
    min_term_months integer NULL,
    contact_phone text NULL,
    contact_email text NULL,
    contact_hours text NULL,
    cancellation_method text NULL,
    payment_contract_id integer NULL,
    imported_from_entry_id integer NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    CONSTRAINT contracts_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE RESTRICT,
    CONSTRAINT contracts_category_id_fkey
        FOREIGN KEY (category_id) REFERENCES contract_management.categories (id) ON DELETE RESTRICT,
    CONSTRAINT contracts_payment_contract_id_fkey
        FOREIGN KEY (payment_contract_id) REFERENCES contract_management.contracts (id) ON DELETE RESTRICT,
    CONSTRAINT contracts_name_not_empty CHECK (char_length(name) > 0),
    CONSTRAINT contracts_status_check CHECK (status IN ('active', 'paused', 'cancelled')),
    CONSTRAINT contracts_password_not_empty CHECK (password IS NULL OR char_length(password) > 0),
    CONSTRAINT contracts_fee_amount_non_negative CHECK (fee_amount IS NULL OR fee_amount >= 0),
    CONSTRAINT contracts_cancel_notice_days_non_negative
        CHECK (cancel_notice_days IS NULL OR cancel_notice_days >= 0),
    CONSTRAINT contracts_min_term_months_non_negative
        CHECK (min_term_months IS NULL OR min_term_months >= 0),
    CONSTRAINT contracts_fee_pair CHECK ((fee_amount IS NULL) = (fee_cycle IS NULL)),
    CONSTRAINT contracts_fee_cycle_check CHECK (fee_cycle IS NULL OR fee_cycle IN ('yearly', 'monthly')),
    CONSTRAINT contracts_date_precision_check
        CHECK (contract_date_precision IS NULL OR contract_date_precision IN ('day', 'month', 'year', 'unknown')),
    CONSTRAINT contracts_date_with_precision
        CHECK (contract_date IS NULL
               OR (contract_date_precision IS NOT NULL AND contract_date_precision <> 'unknown')),
    CONSTRAINT contracts_precision_with_date
        CHECK (contract_date IS NOT NULL
               OR contract_date_precision IS NULL
               OR contract_date_precision = 'unknown'),
    CONSTRAINT contracts_end_date_only_cancelled
        CHECK (end_date IS NULL OR (has_contract AND status = 'cancelled')),
    CONSTRAINT contracts_no_contract_items_null
        CHECK (has_contract
               OR (fee_amount IS NULL AND fee_cycle IS NULL AND renewal_date IS NULL
                   AND contract_date IS NULL AND contract_date_precision IS NULL
                   AND trial_end_date IS NULL AND end_date IS NULL AND auto_renewal IS NULL
                   AND holder_name IS NULL AND member_number IS NULL
                   AND cancel_notice_days IS NULL AND cancellation_fee IS NULL
                   AND min_term_months IS NULL AND contact_phone IS NULL
                   AND contact_email IS NULL AND contact_hours IS NULL
                   AND cancellation_method IS NULL AND payment_contract_id IS NULL)),
    CONSTRAINT contracts_twofa_mail_with_method
        CHECK (twofa_mail_address IS NULL OR login_2fa_mail),
    CONSTRAINT contracts_twofa_tel_with_method
        CHECK (twofa_tel_number IS NULL OR login_2fa_tel),
    CONSTRAINT contracts_payment_not_self
        CHECK (payment_contract_id IS NULL OR payment_contract_id <> id)
);

CREATE INDEX IF NOT EXISTS ix_contracts_user
    ON contract_management.contracts (user_id)
    WHERE is_deleted = false;

CREATE INDEX IF NOT EXISTS ix_contracts_user_category
    ON contract_management.contracts (user_id, category_id)
    WHERE is_deleted = false;

CREATE UNIQUE INDEX IF NOT EXISTS ux_contracts_imported_entry
    ON contract_management.contracts (imported_from_entry_id)
    WHERE imported_from_entry_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_contracts_payment_contract
    ON contract_management.contracts (payment_contract_id)
    WHERE payment_contract_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS contract_management.contract_dependencies (
    contract_id integer NOT NULL,
    depends_on_contract_id integer NOT NULL,
    PRIMARY KEY (contract_id, depends_on_contract_id),
    CONSTRAINT contract_dependencies_contract_fkey
        FOREIGN KEY (contract_id) REFERENCES contract_management.contracts (id) ON DELETE RESTRICT,
    CONSTRAINT contract_dependencies_depends_on_fkey
        FOREIGN KEY (depends_on_contract_id) REFERENCES contract_management.contracts (id) ON DELETE RESTRICT,
    CONSTRAINT contract_dependencies_not_self CHECK (contract_id <> depends_on_contract_id)
);

CREATE INDEX IF NOT EXISTS ix_contract_dependencies_target
    ON contract_management.contract_dependencies (depends_on_contract_id);

CREATE TABLE IF NOT EXISTS contract_management.cancellation_plan (
    user_id integer NOT NULL,
    contract_id integer NOT NULL,
    position integer NOT NULL,
    PRIMARY KEY (user_id, contract_id),
    CONSTRAINT cancellation_plan_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE RESTRICT,
    CONSTRAINT cancellation_plan_contract_id_fkey
        FOREIGN KEY (contract_id) REFERENCES contract_management.contracts (id) ON DELETE RESTRICT,
    CONSTRAINT cancellation_plan_position_check CHECK (position >= 1),
    CONSTRAINT ux_cancellation_plan_position
        UNIQUE (user_id, position) DEFERRABLE INITIALLY DEFERRED
);
