-- note-management（ノート管理）のスキーマ。db-design.md に対応する。
-- 何度実行しても同じ結果になる（IF NOT EXISTS）。

CREATE SCHEMA IF NOT EXISTS note_management;

-- フォルダ（parent_id が NULL の行がルートフォルダ）。論理削除する。
CREATE TABLE IF NOT EXISTS note_management.folders (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     integer NOT NULL,
    parent_id   integer NULL,
    name        text NOT NULL,
    sort_order  integer NOT NULL,
    is_deleted  boolean NOT NULL DEFAULT false,
    CONSTRAINT folders_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE RESTRICT,
    CONSTRAINT folders_parent_id_fkey
        FOREIGN KEY (parent_id) REFERENCES note_management.folders (id),
    CONSTRAINT folders_name_not_blank CHECK (char_length(btrim(name)) > 0)
);

-- 同名の判定は、削除されていない行だけ。NULL の親は通常の一意制約では重複できるため、ルートと子で分ける。
CREATE UNIQUE INDEX IF NOT EXISTS folders_root_name_uidx
    ON note_management.folders (user_id, name)
    WHERE parent_id IS NULL AND NOT is_deleted;

CREATE UNIQUE INDEX IF NOT EXISTS folders_child_name_uidx
    ON note_management.folders (user_id, parent_id, name)
    WHERE parent_id IS NOT NULL AND NOT is_deleted;

-- 並び順は、削除済みを含めて、同じ親の中で一意。
CREATE UNIQUE INDEX IF NOT EXISTS folders_root_order_uidx
    ON note_management.folders (user_id, sort_order)
    WHERE parent_id IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS folders_child_order_uidx
    ON note_management.folders (user_id, parent_id, sort_order)
    WHERE parent_id IS NOT NULL;

-- ファイル（必ずフォルダの中）。論理削除する。
CREATE TABLE IF NOT EXISTS note_management.files (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     integer NOT NULL,
    folder_id   integer NOT NULL,
    title       text NOT NULL,
    sort_order  integer NOT NULL,
    is_deleted  boolean NOT NULL DEFAULT false,
    CONSTRAINT files_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE RESTRICT,
    CONSTRAINT files_folder_id_fkey
        FOREIGN KEY (folder_id) REFERENCES note_management.folders (id),
    CONSTRAINT files_title_not_blank CHECK (char_length(btrim(title)) > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS files_title_uidx
    ON note_management.files (user_id, folder_id, title)
    WHERE NOT is_deleted;

CREATE UNIQUE INDEX IF NOT EXISTS files_order_uidx
    ON note_management.files (user_id, folder_id, sort_order);

-- パーツ。論理削除する。
CREATE TABLE IF NOT EXISTS note_management.parts (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      integer NOT NULL,
    file_id      integer NOT NULL,
    sort_order   integer NOT NULL,
    is_deleted   boolean NOT NULL DEFAULT false,
    ptype        text NOT NULL,
    data         text NOT NULL DEFAULT '',
    byte_size    integer NOT NULL DEFAULT 0,
    filename     text NOT NULL DEFAULT '',
    title        text NOT NULL DEFAULT '',
    markers      jsonb NOT NULL DEFAULT '[]'::jsonb,
    image_scale  real NOT NULL DEFAULT 1.0,
    CONSTRAINT parts_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE RESTRICT,
    CONSTRAINT parts_file_id_fkey
        FOREIGN KEY (file_id) REFERENCES note_management.files (id),
    CONSTRAINT parts_ptype_check
        CHECK (ptype IN ('text', 'md', 'tex', 'url', 'action', 'checklist', 'jpeg', 'png', 'binary')),
    CONSTRAINT parts_filename_required
        CHECK (ptype NOT IN ('jpeg', 'png', 'binary') OR char_length(btrim(filename)) > 0),
    CONSTRAINT parts_byte_size_check CHECK (byte_size >= 0),
    CONSTRAINT parts_image_scale_check CHECK (image_scale >= 0.25 AND image_scale <= 4.0),
    CONSTRAINT parts_markers_array CHECK (jsonb_typeof(markers) = 'array')
);

CREATE UNIQUE INDEX IF NOT EXISTS parts_order_uidx
    ON note_management.parts (user_id, file_id, sort_order);

-- 画像・バイナリの過去世代
CREATE TABLE IF NOT EXISTS note_management.part_revisions (
    id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          integer NOT NULL,
    part_id          integer NOT NULL,
    revision_number  integer NOT NULL,
    ptype            text NOT NULL,
    filename         text NOT NULL,
    data             text NOT NULL,
    byte_size        integer NOT NULL DEFAULT 0,
    created_at       timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT part_revisions_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE RESTRICT,
    CONSTRAINT part_revisions_part_id_fkey
        FOREIGN KEY (part_id) REFERENCES note_management.parts (id) ON DELETE CASCADE,
    CONSTRAINT part_revisions_number_uq UNIQUE (part_id, revision_number),
    CONSTRAINT part_revisions_ptype_check CHECK (ptype IN ('jpeg', 'png', 'binary')),
    CONSTRAINT part_revisions_byte_size_check CHECK (byte_size >= 0)
);

-- チェックリスト（パーツと 1 対 1）
CREATE TABLE IF NOT EXISTS note_management.checklists (
    id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id  integer NOT NULL,
    part_id  integer NOT NULL,
    title    text NOT NULL DEFAULT '',
    CONSTRAINT checklists_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE RESTRICT,
    CONSTRAINT checklists_part_id_fkey
        FOREIGN KEY (part_id) REFERENCES note_management.parts (id) ON DELETE CASCADE,
    CONSTRAINT checklists_part_id_uq UNIQUE (part_id)
);

-- チェックリストのカテゴリ（名前が空のものは無名カテゴリ）。論理削除する。
CREATE TABLE IF NOT EXISTS note_management.checklist_categories (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    checklist_id  integer NOT NULL,
    name          text NOT NULL DEFAULT '',
    sort_order    integer NOT NULL DEFAULT 0,
    is_deleted    boolean NOT NULL DEFAULT false,
    CONSTRAINT checklist_categories_checklist_id_fkey
        FOREIGN KEY (checklist_id) REFERENCES note_management.checklists (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS checklist_categories_name_uidx
    ON note_management.checklist_categories (checklist_id, name)
    WHERE NOT is_deleted;

CREATE INDEX IF NOT EXISTS checklist_categories_order_idx
    ON note_management.checklist_categories (checklist_id, sort_order);

-- チェック項目。論理削除する。
CREATE TABLE IF NOT EXISTS note_management.checklist_items (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    checklist_id  integer NOT NULL,
    category_id   integer NOT NULL,
    title         text NOT NULL DEFAULT '',
    is_checked    boolean NOT NULL DEFAULT false,
    sort_order    integer NOT NULL DEFAULT 0,
    is_deleted    boolean NOT NULL DEFAULT false,
    CONSTRAINT checklist_items_checklist_id_fkey
        FOREIGN KEY (checklist_id) REFERENCES note_management.checklists (id) ON DELETE CASCADE,
    CONSTRAINT checklist_items_category_id_fkey
        FOREIGN KEY (category_id) REFERENCES note_management.checklist_categories (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS checklist_items_order_idx
    ON note_management.checklist_items (category_id, sort_order);

CREATE INDEX IF NOT EXISTS checklist_items_checklist_idx
    ON note_management.checklist_items (checklist_id);
