CREATE SCHEMA IF NOT EXISTS goods_management;

CREATE TABLE IF NOT EXISTS goods_management.persons (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    integer NOT NULL,
    name       text    NOT NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    CONSTRAINT persons_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE RESTRICT,
    CONSTRAINT persons_name_not_empty CHECK (char_length(name) > 0)
);

CREATE INDEX IF NOT EXISTS persons_user_active_idx
    ON goods_management.persons (user_id)
    WHERE is_deleted = false;

CREATE TABLE IF NOT EXISTS goods_management.artists (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    integer NOT NULL,
    name       text    NOT NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    CONSTRAINT artists_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE RESTRICT,
    CONSTRAINT artists_name_not_empty CHECK (char_length(name) > 0)
);

CREATE INDEX IF NOT EXISTS artists_user_active_idx
    ON goods_management.artists (user_id)
    WHERE is_deleted = false;

CREATE TABLE IF NOT EXISTS goods_management.artist_persons (
    id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id   integer NOT NULL,
    artist_id integer NOT NULL,
    person_id integer NOT NULL,
    CONSTRAINT artist_persons_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE RESTRICT,
    CONSTRAINT artist_persons_artist_id_fkey
        FOREIGN KEY (artist_id) REFERENCES goods_management.artists (id) ON DELETE RESTRICT,
    CONSTRAINT artist_persons_person_id_fkey
        FOREIGN KEY (person_id) REFERENCES goods_management.persons (id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX IF NOT EXISTS artist_persons_artist_person_uidx
    ON goods_management.artist_persons (artist_id, person_id);

CREATE INDEX IF NOT EXISTS artist_persons_person_idx
    ON goods_management.artist_persons (person_id);

CREATE TABLE IF NOT EXISTS goods_management.media (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    integer NOT NULL,
    name       text    NOT NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    CONSTRAINT media_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE RESTRICT,
    CONSTRAINT media_name_not_empty CHECK (char_length(name) > 0)
);

CREATE INDEX IF NOT EXISTS media_user_active_idx
    ON goods_management.media (user_id)
    WHERE is_deleted = false;

CREATE TABLE IF NOT EXISTS goods_management.goods (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      integer NOT NULL,
    media_id     integer NOT NULL,
    artist_id    integer NOT NULL,
    title        text    NOT NULL,
    release_date date    NOT NULL,
    memo         text,
    is_owned     boolean NOT NULL DEFAULT false,
    code_number  text,
    is_deleted   boolean NOT NULL DEFAULT false,
    CONSTRAINT goods_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE RESTRICT,
    CONSTRAINT goods_media_id_fkey
        FOREIGN KEY (media_id) REFERENCES goods_management.media (id) ON DELETE RESTRICT,
    CONSTRAINT goods_artist_id_fkey
        FOREIGN KEY (artist_id) REFERENCES goods_management.artists (id) ON DELETE RESTRICT,
    CONSTRAINT goods_title_not_empty CHECK (char_length(title) > 0)
);

CREATE INDEX IF NOT EXISTS goods_user_artist_active_idx
    ON goods_management.goods (user_id, artist_id)
    WHERE is_deleted = false;

CREATE INDEX IF NOT EXISTS goods_user_media_active_idx
    ON goods_management.goods (user_id, media_id)
    WHERE is_deleted = false;

CREATE TABLE IF NOT EXISTS goods_management.goods_images (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       integer NOT NULL,
    goods_id      integer NOT NULL,
    image_data    bytea   NOT NULL,
    image_type    text    NOT NULL,
    display_order integer NOT NULL,
    CONSTRAINT goods_images_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE RESTRICT,
    CONSTRAINT goods_images_goods_id_fkey
        FOREIGN KEY (goods_id) REFERENCES goods_management.goods (id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS goods_images_goods_idx
    ON goods_management.goods_images (goods_id);
