-- movie-management（動画管理・視聴）のスキーマ。db-design.md に対応する。
-- 何度実行しても同じ結果になる（IF NOT EXISTS / ON CONFLICT DO NOTHING）。

CREATE SCHEMA IF NOT EXISTS movie_management;

-- ジャンル（user_id が NULL の行は全利用者共通）
CREATE TABLE IF NOT EXISTS movie_management.genres (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     integer NULL,
    name        varchar(100) NOT NULL,
    sort_order  integer NOT NULL DEFAULT 0,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT genres_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE RESTRICT,
    CONSTRAINT genres_name_not_empty CHECK (char_length(name) > 0),
    CONSTRAINT genres_sort_order_check CHECK (sort_order >= 0)
);

-- NULL は通常の一意制約では重複できるため、共通と独自で部分一意に分ける
CREATE UNIQUE INDEX IF NOT EXISTS genres_system_name_uidx
    ON movie_management.genres (name)
    WHERE user_id IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS genres_user_name_uidx
    ON movie_management.genres (user_id, name)
    WHERE user_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS genres_sort_idx
    ON movie_management.genres (sort_order, id);

-- 作品
CREATE TABLE IF NOT EXISTS movie_management.series (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      integer NOT NULL,
    title        varchar(500) NOT NULL,
    description  text NULL,
    created_at   timestamptz NOT NULL DEFAULT now(),
    updated_at   timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT series_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE RESTRICT,
    CONSTRAINT series_title_not_empty CHECK (char_length(title) > 0)
);

CREATE INDEX IF NOT EXISTS series_user_created_idx
    ON movie_management.series (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS series_user_title_idx
    ON movie_management.series (user_id, title);

-- 動画のメタ情報（動画ファイル本体は video_chunks）
CREATE TABLE IF NOT EXISTS movie_management.videos (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          integer NOT NULL,
    series_id        integer NULL,
    title            varchar(500) NOT NULL,
    description      text NULL,
    episode_number   integer NULL,
    episode_title    varchar(500) NULL,
    sort_order       integer NOT NULL DEFAULT 0,
    duration_ms      bigint NOT NULL,
    mime_type        varchar(100) NOT NULL DEFAULT 'video/mp4',
    file_size_bytes  bigint NOT NULL DEFAULT 0,
    chunk_count      integer NOT NULL DEFAULT 0,
    status           varchar(20) NOT NULL DEFAULT 'uploading',
    created_at       timestamptz NOT NULL DEFAULT now(),
    updated_at       timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT videos_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE RESTRICT,
    CONSTRAINT videos_series_id_fkey
        FOREIGN KEY (series_id) REFERENCES movie_management.series (id) ON DELETE RESTRICT,
    CONSTRAINT videos_series_episode_key UNIQUE (series_id, episode_number),
    CONSTRAINT videos_title_not_empty CHECK (char_length(title) > 0),
    CONSTRAINT videos_duration_check CHECK (duration_ms >= 1 AND duration_ms <= 14400000),
    CONSTRAINT videos_file_size_check CHECK (file_size_bytes >= 0),
    CONSTRAINT videos_chunk_count_check CHECK (chunk_count >= 0),
    CONSTRAINT videos_sort_order_check CHECK (sort_order >= 0),
    CONSTRAINT videos_episode_number_check CHECK (episode_number IS NULL OR episode_number >= 1),
    CONSTRAINT videos_status_check CHECK (status IN ('uploading', 'ready', 'error')),
    CONSTRAINT videos_ready_has_chunks_check CHECK (status <> 'ready' OR chunk_count > 0)
);

CREATE INDEX IF NOT EXISTS videos_user_status_created_idx
    ON movie_management.videos (user_id, status, created_at DESC);

CREATE INDEX IF NOT EXISTS videos_user_title_idx
    ON movie_management.videos (user_id, title);

CREATE INDEX IF NOT EXISTS videos_series_sort_idx
    ON movie_management.videos (series_id, sort_order);

CREATE INDEX IF NOT EXISTS videos_user_standalone_idx
    ON movie_management.videos (user_id, created_at)
    WHERE series_id IS NULL AND status = 'ready';

-- 動画とジャンルの関連
CREATE TABLE IF NOT EXISTS movie_management.video_genres (
    video_id    bigint NOT NULL,
    genre_id    integer NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT video_genres_pkey PRIMARY KEY (video_id, genre_id),
    CONSTRAINT video_genres_video_id_fkey
        FOREIGN KEY (video_id) REFERENCES movie_management.videos (id) ON DELETE CASCADE,
    CONSTRAINT video_genres_genre_id_fkey
        FOREIGN KEY (genre_id) REFERENCES movie_management.genres (id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS video_genres_genre_idx
    ON movie_management.video_genres (genre_id);

-- 動画ファイル本体の断片（チャンク）
CREATE TABLE IF NOT EXISTS movie_management.video_chunks (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_id       bigint NOT NULL,
    chunk_index    integer NOT NULL,
    start_time_ms  bigint NOT NULL,
    end_time_ms    bigint NOT NULL,
    byte_length    integer NOT NULL,
    data           bytea NOT NULL,
    created_at     timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT video_chunks_video_id_fkey
        FOREIGN KEY (video_id) REFERENCES movie_management.videos (id) ON DELETE CASCADE,
    CONSTRAINT video_chunks_video_index_key UNIQUE (video_id, chunk_index),
    CONSTRAINT video_chunks_index_check CHECK (chunk_index >= 0),
    CONSTRAINT video_chunks_time_check CHECK (start_time_ms >= 0 AND end_time_ms > start_time_ms),
    CONSTRAINT video_chunks_byte_length_check CHECK (byte_length > 0),
    CONSTRAINT video_chunks_data_length_check CHECK (octet_length(data) = byte_length)
);

CREATE INDEX IF NOT EXISTS video_chunks_seek_idx
    ON movie_management.video_chunks (video_id, start_time_ms);

-- 動画ファイルは既に圧縮されているため、列の圧縮はしない
ALTER TABLE movie_management.video_chunks ALTER COLUMN data SET STORAGE EXTERNAL;

-- サムネイル（1 動画 1 枚）
CREATE TABLE IF NOT EXISTS movie_management.thumbnails (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_id    bigint NOT NULL,
    mime_type   varchar(50) NOT NULL DEFAULT 'image/jpeg',
    width       integer NULL,
    height      integer NULL,
    data        bytea NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT thumbnails_video_id_fkey
        FOREIGN KEY (video_id) REFERENCES movie_management.videos (id) ON DELETE CASCADE,
    CONSTRAINT thumbnails_video_id_key UNIQUE (video_id),
    CONSTRAINT thumbnails_data_check CHECK (octet_length(data) > 0)
);

-- 利用者ごと・動画ごとの再生状態
CREATE TABLE IF NOT EXISTS movie_management.playback_states (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         integer NOT NULL,
    video_id        bigint NOT NULL,
    position_ms     bigint NOT NULL DEFAULT 0,
    completed       boolean NOT NULL DEFAULT false,
    play_count      integer NOT NULL DEFAULT 0,
    last_played_at  timestamptz NOT NULL DEFAULT now(),
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT playback_states_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE RESTRICT,
    CONSTRAINT playback_states_video_id_fkey
        FOREIGN KEY (video_id) REFERENCES movie_management.videos (id) ON DELETE CASCADE,
    CONSTRAINT playback_states_user_video_key UNIQUE (user_id, video_id),
    CONSTRAINT playback_states_position_check CHECK (position_ms >= 0),
    CONSTRAINT playback_states_play_count_check CHECK (play_count >= 0)
);

CREATE INDEX IF NOT EXISTS playback_states_user_last_idx
    ON movie_management.playback_states (user_id, last_played_at DESC);

CREATE INDEX IF NOT EXISTS playback_states_video_idx
    ON movie_management.playback_states (video_id);

-- プレイリスト
CREATE TABLE IF NOT EXISTS movie_management.playlists (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      integer NOT NULL,
    name         varchar(500) NOT NULL,
    description  text NULL,
    created_at   timestamptz NOT NULL DEFAULT now(),
    updated_at   timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT playlists_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE RESTRICT,
    CONSTRAINT playlists_name_not_empty CHECK (char_length(name) > 0)
);

CREATE INDEX IF NOT EXISTS playlists_user_updated_idx
    ON movie_management.playlists (user_id, updated_at DESC);

CREATE INDEX IF NOT EXISTS playlists_user_name_idx
    ON movie_management.playlists (user_id, name);

-- プレイリストに含める動画と並び（同じ動画を複数回含めてよい）
CREATE TABLE IF NOT EXISTS movie_management.playlist_items (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    playlist_id  integer NOT NULL,
    video_id     bigint NOT NULL,
    sort_order   integer NOT NULL,
    created_at   timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT playlist_items_playlist_id_fkey
        FOREIGN KEY (playlist_id) REFERENCES movie_management.playlists (id) ON DELETE CASCADE,
    CONSTRAINT playlist_items_video_id_fkey
        FOREIGN KEY (video_id) REFERENCES movie_management.videos (id) ON DELETE CASCADE,
    CONSTRAINT playlist_items_playlist_sort_key UNIQUE (playlist_id, sort_order),
    CONSTRAINT playlist_items_sort_order_check CHECK (sort_order >= 0)
);

CREATE INDEX IF NOT EXISTS playlist_items_video_idx
    ON movie_management.playlist_items (video_id);

-- 続きから視聴の情報（利用者 1 人 1 行）
CREATE TABLE IF NOT EXISTS movie_management.playback_contexts (
    user_id                    integer PRIMARY KEY,
    last_video_id              bigint NULL,
    last_video_position_ms     bigint NOT NULL DEFAULT 0,
    last_video_updated_at      timestamptz NULL,
    last_playlist_id           integer NULL,
    last_playlist_item_id      bigint NULL,
    last_playlist_position_ms  bigint NOT NULL DEFAULT 0,
    last_playlist_updated_at   timestamptz NULL,
    updated_at                 timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT playback_contexts_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE RESTRICT,
    CONSTRAINT playback_contexts_last_video_id_fkey
        FOREIGN KEY (last_video_id) REFERENCES movie_management.videos (id) ON DELETE SET NULL,
    CONSTRAINT playback_contexts_last_playlist_id_fkey
        FOREIGN KEY (last_playlist_id) REFERENCES movie_management.playlists (id) ON DELETE SET NULL,
    CONSTRAINT playback_contexts_last_playlist_item_id_fkey
        FOREIGN KEY (last_playlist_item_id) REFERENCES movie_management.playlist_items (id) ON DELETE SET NULL,
    CONSTRAINT playback_contexts_video_position_check CHECK (last_video_position_ms >= 0),
    CONSTRAINT playback_contexts_playlist_position_check CHECK (last_playlist_position_ms >= 0)
);

CREATE INDEX IF NOT EXISTS playback_contexts_video_idx
    ON movie_management.playback_contexts (last_video_id);

CREATE INDEX IF NOT EXISTS playback_contexts_playlist_idx
    ON movie_management.playback_contexts (last_playlist_id);

CREATE INDEX IF NOT EXISTS playback_contexts_item_idx
    ON movie_management.playback_contexts (last_playlist_item_id);

-- 全利用者共通のジャンル（初期データ）
INSERT INTO movie_management.genres (user_id, name, sort_order)
VALUES
    (NULL, '洋画', 1),
    (NULL, '邦画', 2),
    (NULL, 'アニメ', 3),
    (NULL, 'ライブ', 4),
    (NULL, 'ドラマ', 5),
    (NULL, 'ドキュメンタリー', 6),
    (NULL, 'その他', 99)
ON CONFLICT (name) WHERE user_id IS NULL DO NOTHING;
