CREATE TABLE IF NOT EXISTS expense_management.budget_periods (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL,
    title varchar(255) NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    CONSTRAINT budget_periods_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE RESTRICT,
    CONSTRAINT budget_periods_title_not_empty CHECK (char_length(title) > 0),
    CONSTRAINT budget_periods_range CHECK (end_date >= start_date)
);

CREATE INDEX IF NOT EXISTS budget_periods_user_range_idx
    ON expense_management.budget_periods (user_id, start_date, end_date);

CREATE TABLE IF NOT EXISTS expense_management.budget_items (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL,
    budget_period_id integer NOT NULL,
    name varchar(255) NOT NULL,
    amount numeric(12, 2) NOT NULL,
    display_order integer NOT NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    CONSTRAINT budget_items_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE RESTRICT,
    CONSTRAINT budget_items_budget_period_id_fkey
        FOREIGN KEY (budget_period_id) REFERENCES expense_management.budget_periods (id) ON DELETE RESTRICT,
    CONSTRAINT budget_items_name_not_empty CHECK (char_length(name) > 0),
    CONSTRAINT budget_items_amount_non_negative CHECK (amount >= 0)
);

CREATE INDEX IF NOT EXISTS budget_items_period_order_active_idx
    ON expense_management.budget_items (budget_period_id, display_order)
    WHERE is_deleted = false;

CREATE TABLE IF NOT EXISTS expense_management.payment_methods (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL,
    name varchar(255) NOT NULL,
    closing_day smallint NOT NULL,
    closing_day_shift_direction varchar(16) NULL,
    payment_month_offset smallint NOT NULL,
    payment_day smallint NOT NULL,
    payment_day_shift_direction varchar(16) NULL,
    display_order integer NOT NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    CONSTRAINT payment_methods_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE RESTRICT,
    CONSTRAINT payment_methods_name_not_empty CHECK (char_length(name) > 0),
    CONSTRAINT payment_methods_closing_day_range CHECK (closing_day BETWEEN 0 AND 31),
    CONSTRAINT payment_methods_shift_direction_values CHECK (
        (closing_day_shift_direction IS NULL OR closing_day_shift_direction IN ('earlier', 'later'))
        AND (payment_day_shift_direction IS NULL OR payment_day_shift_direction IN ('earlier', 'later'))
    ),
    CONSTRAINT payment_methods_immediate_fixed_values CHECK (
        (
            closing_day = 0
            AND payment_month_offset = 0
            AND payment_day = 0
            AND closing_day_shift_direction IS NULL
            AND payment_day_shift_direction IS NULL
        )
        OR (
            closing_day > 0
            AND payment_month_offset >= 0
            AND payment_day BETWEEN 1 AND 31
            AND closing_day_shift_direction IS NOT NULL
            AND payment_day_shift_direction IS NOT NULL
        )
    )
);

CREATE INDEX IF NOT EXISTS payment_methods_user_order_active_idx
    ON expense_management.payment_methods (user_id, display_order)
    WHERE is_deleted = false;

CREATE TABLE IF NOT EXISTS expense_management.payment_method_exclusions (
    payment_method_id integer NOT NULL,
    target varchar(16) NOT NULL,
    exclusion_kind varchar(16) NOT NULL,
    PRIMARY KEY (payment_method_id, target, exclusion_kind),
    CONSTRAINT payment_method_exclusions_payment_method_id_fkey
        FOREIGN KEY (payment_method_id) REFERENCES expense_management.payment_methods (id) ON DELETE RESTRICT,
    CONSTRAINT payment_method_exclusions_target_check
        CHECK (target IN ('closing_day', 'payment_day')),
    CONSTRAINT payment_method_exclusions_kind_check CHECK (
        exclusion_kind IN (
            'sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday',
            'nonexistent_day'
        )
    )
);

CREATE INDEX IF NOT EXISTS payment_method_exclusions_method_idx
    ON expense_management.payment_method_exclusions (payment_method_id);

CREATE TABLE IF NOT EXISTS expense_management.expenses (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL,
    budget_item_id integer NOT NULL,
    payment_method_id integer NOT NULL,
    usage_date date NOT NULL,
    purpose varchar(255) NOT NULL,
    amount numeric(12, 2) NOT NULL,
    memo text NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    payment_date date NOT NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    CONSTRAINT expenses_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE RESTRICT,
    CONSTRAINT expenses_budget_item_id_fkey
        FOREIGN KEY (budget_item_id) REFERENCES expense_management.budget_items (id) ON DELETE RESTRICT,
    CONSTRAINT expenses_payment_method_id_fkey
        FOREIGN KEY (payment_method_id) REFERENCES expense_management.payment_methods (id) ON DELETE RESTRICT,
    CONSTRAINT expenses_purpose_not_empty CHECK (char_length(purpose) > 0),
    CONSTRAINT expenses_amount_non_negative CHECK (amount >= 0)
);

CREATE INDEX IF NOT EXISTS expenses_user_usage_date_active_idx
    ON expense_management.expenses (user_id, usage_date)
    WHERE is_deleted = false;

CREATE INDEX IF NOT EXISTS expenses_user_payment_date_active_idx
    ON expense_management.expenses (user_id, payment_date)
    WHERE is_deleted = false;

CREATE INDEX IF NOT EXISTS expenses_budget_item_active_idx
    ON expense_management.expenses (budget_item_id)
    WHERE is_deleted = false;
